# Generated by Django 5.2.8 on 2025-11-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=250)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
